In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('EasyVisa.csv')
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [4]:
df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [6]:
data = df.to_dict(orient='records')
data

[{'case_id': 'EZYV01',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 14513,
  'yr_of_estab': 2007,
  'region_of_employment': 'West',
  'prevailing_wage': 592.2029,
  'unit_of_wage': 'Hour',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV02',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2412,
  'yr_of_estab': 2002,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 83425.65,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV03',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'Y',
  'no_of_employees': 44444,
  'yr_of_estab': 2008,
  'region_of_employment': 'West',
  'prevailing_wage': 122996.86,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV04',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 98,
  'yr_of_estab': 1897,
  'region_of_employment': 'West',
  'prevailing_wage': 83434.03,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV05',
  'continent': 'Africa',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1082,
  'yr_of_estab': 2005,
  'region_of_employment': 'South',
  'prevailing_wage': 149907.39,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV06',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2339,
  'yr_of_estab': 2012,
  'region_of_employment': 'South',
  'prevailing_wage': 78252.14,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV07',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 4985,
  'yr_of_estab': 1994,
  'region_of_employment': 'South',
  'prevailing_wage': 53635.39,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV08',
  'continent': 'North America',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 3035,
  'yr_of_estab': 1924,
  'region_of_employment': 'West',
  'prevailing_wage': 418.2298,
  'unit_of_wage': 'Hour',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV09',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 4810,
  'yr_of_estab': 2012,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 74362.19,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV10',
  'continent': 'Europe',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2251,
  'yr_of_estab': 1995,
  'region_of_employment': 'South',
  'prevailing_wage': 67514.76,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV11',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 2465,
  'yr_of_estab': 2004,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 83588.56,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV12',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 4069,
  'yr_of_estab': 2005,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 70813.09,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV13',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 123876,
  'yr_of_estab': 1963,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 28663.05,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV14',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1652,
  'yr_of_estab': 2007,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 107196.03,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV15',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 15756,
  'yr_of_estab': 2006,
  'region_of_employment': 'South',
  'prevailing_wage': 220081.73,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV16',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 4897,
  'yr_of_estab': 1987,
  'region_of_employment': 'West',
  'prevailing_wage': 74108.02,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV17',
  'continent': 'Europe',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 76638,
  'yr_of_estab': 1991,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 3706.79,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV18',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2747,
  'yr_of_estab': 2001,
  'region_of_employment': 'West',
  'prevailing_wage': 16132.61,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV19',
  'continent': 'Africa',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 4743,
  'yr_of_estab': 2004,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 150441.13,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV20',
  'continent': 'Asia',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 843,
  'yr_of_estab': 1972,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 79948.12,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV21',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 880,
  'yr_of_estab': 2008,
  'region_of_employment': 'West',
  'prevailing_wage': 71128.98,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV22',
  'continent': 'North America',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1706,
  'yr_of_estab': 2013,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 137694.98,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV23',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2878,
  'yr_of_estab': 1968,
  'region_of_employment': 'West',
  'prevailing_wage': 45642.39,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV24',
  'continent': 'North America',
  'education_of_employee': 'High School',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1517,
  'yr_of_estab': 1884,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 90108.38,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV25',
  'continent': 'Europe',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 241,
  'yr_of_estab': 1981,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 71286.04,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV26',
  'continent': 'North America',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1100,
  'yr_of_estab': 1997,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 99489.65,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV27',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 756,
  'yr_of_estab': 1995,
  'region_of_employment': 'South',
  'prevailing_wage': 86332.95,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV28',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 2889,
  'yr_of_estab': 2005,
  'region_of_employment': 'South',
  'prevailing_wage': 103029.33,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV29',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 18,
  'yr_of_estab': 2004,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 40925.86,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV30',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 758,
  'yr_of_estab': 2009,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 189190.48,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV31',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1408,
  'yr_of_estab': 1998,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 79594.12,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV32',
  'continent': 'Asia',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 995,
  'yr_of_estab': 1880,
  'region_of_employment': 'South',
  'prevailing_wage': 135866.13,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV33',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 2415,
  'yr_of_estab': 1963,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 72077.57,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV34',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 2395,
  'yr_of_estab': 2000,
  'region_of_employment': 'South',
  'prevailing_wage': 81921.18,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV35',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1809,
  'yr_of_estab': 2010,
  'region_of_employment': 'South',
  'prevailing_wage': 225569.73,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV36',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 5512,
  'yr_of_estab': 2001,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 92421.92,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV37',
  'continent': 'Europe',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2520,
  'yr_of_estab': 1981,
  'region_of_employment': 'West',
  'prevailing_wage': 2490.12,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV38',
  'continent': 'Europe',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 44,
  'yr_of_estab': 1965,
  'region_of_employment': 'South',
  'prevailing_wage': 110817.26,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV39',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 2206,
  'yr_of_estab': 1909,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 50960.01,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV40',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 3729,
  'yr_of_estab': 2007,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 125336.9,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV41',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 3723,
  'yr_of_estab': 2011,
  'region_of_employment': 'West',
  'prevailing_wage': 39633.32,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV42',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1209,
  'yr_of_estab': 1989,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 156326.33,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV43',
  'continent': 'Europe',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 19770,
  'yr_of_estab': 2005,
  'region_of_employment': 'West',
  'prevailing_wage': 43630.58,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV44',
  'continent': 'North America',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2582,
  'yr_of_estab': 1989,
  'region_of_employment': 'South',
  'prevailing_wage': 54614.42,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV45',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 5407,
  'yr_of_estab': 1998,
  'region_of_employment': 'West',
  'prevailing_wage': 28989.87,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV46',
  'continent': 'Europe',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'Y',
  'no_of_employees': 2092,
  'yr_of_estab': 1998,
  'region_of_employment': 'South',
  'prevailing_wage': 22924.91,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV47',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2623,
  'yr_of_estab': 2008,
  'region_of_employment': 'South',
  'prevailing_wage': 61567.75,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV48',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 226,
  'yr_of_estab': 1991,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 156251.17,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV49',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2405,
  'yr_of_estab': 1933,
  'region_of_employment': 'South',
  'prevailing_wage': 86022.02,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV50',
  'continent': 'Asia',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'N',
  'requires_job_training': 'Y',
  'no_of_employees': 2171,
  'yr_of_estab': 1960,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 49565.37,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV51',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 746,
  'yr_of_estab': 1991,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 66191.41,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV52',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 3129,
  'yr_of_estab': 2003,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 95623.2,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV53',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1647,
  'yr_of_estab': 1998,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 115014.05,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV54',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2438,
  'yr_of_estab': 1976,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 35018.04,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV55',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 11733,
  'yr_of_estab': 1995,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 230.8072,
  'unit_of_wage': 'Hour',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV56',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2368,
  'yr_of_estab': 1998,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 113799.64,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV57',
  'continent': 'Europe',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 779,
  'yr_of_estab': 1994,
  'region_of_employment': 'West',
  'prevailing_wage': 85854.09,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',

In [ ]:
DB_NAME = "US_VISA_DB"
COLLECTION_NAME = "VISA_DATA_COLLECTION"
CONNECTION_URL = ""

In [29]:
from pymongo import MongoClient

In [17]:
client = MongoClient(CONNECTION_URL)
db = client[DB_NAME]
collection = db[COLLECTION_NAME]

In [19]:
records = collection.insert_many(data)
records

InsertManyResult([ObjectId('69df560eb3ce5a690a18995c'), ObjectId('69df560eb3ce5a690a18995d'), ObjectId('69df560eb3ce5a690a18995e'), ObjectId('69df560eb3ce5a690a18995f'), ObjectId('69df560eb3ce5a690a189960'), ObjectId('69df560eb3ce5a690a189961'), ObjectId('69df560eb3ce5a690a189962'), ObjectId('69df560eb3ce5a690a189963'), ObjectId('69df560eb3ce5a690a189964'), ObjectId('69df560eb3ce5a690a189965'), ObjectId('69df560eb3ce5a690a189966'), ObjectId('69df560eb3ce5a690a189967'), ObjectId('69df560eb3ce5a690a189968'), ObjectId('69df560eb3ce5a690a189969'), ObjectId('69df560eb3ce5a690a18996a'), ObjectId('69df560eb3ce5a690a18996b'), ObjectId('69df560eb3ce5a690a18996c'), ObjectId('69df560eb3ce5a690a18996d'), ObjectId('69df560eb3ce5a690a18996e'), ObjectId('69df560eb3ce5a690a18996f'), ObjectId('69df560eb3ce5a690a189970'), ObjectId('69df560eb3ce5a690a189971'), ObjectId('69df560eb3ce5a690a189972'), ObjectId('69df560eb3ce5a690a189973'), ObjectId('69df560eb3ce5a690a189974'), ObjectId('69df560eb3ce5a690a189975'), ObjectId('69df560eb3ce5a690a189976'), ObjectId('69df560eb3ce5a690a189977'), ObjectId('69df560eb3ce5a690a189978'), ObjectId('69df560eb3ce5a690a189979'), ObjectId('69df560eb3ce5a690a18997a'), ObjectId('69df560eb3ce5a690a18997b'), ObjectId('69df560eb3ce5a690a18997c'), ObjectId('69df560eb3ce5a690a18997d'), ObjectId('69df560eb3ce5a690a18997e'), ObjectId('69df560eb3ce5a690a18997f'), ObjectId('69df560eb3ce5a690a189980'), ObjectId('69df560eb3ce5a690a189981'), ObjectId('69df560eb3ce5a690a189982'), ObjectId('69df560eb3ce5a690a189983'), ObjectId('69df560eb3ce5a690a189984'), ObjectId('69df560eb3ce5a690a189985'), ObjectId('69df560eb3ce5a690a189986'), ObjectId('69df560eb3ce5a690a189987'), ObjectId('69df560eb3ce5a690a189988'), ObjectId('69df560eb3ce5a690a189989'), ObjectId('69df560eb3ce5a690a18998a'), ObjectId('69df560eb3ce5a690a18998b'), ObjectId('69df560eb3ce5a690a18998c'), ObjectId('69df560eb3ce5a690a18998d'), ObjectId('69df560eb3ce5a690a18998e'), ObjectId('69df560eb3ce5a690a18998f'), ObjectId('69df560eb3ce5a690a189990'), ObjectId('69df560eb3ce5a690a189991'), ObjectId('69df560eb3ce5a690a189992'), ObjectId('69df560eb3ce5a690a189993'), ObjectId('69df560eb3ce5a690a189994'), ObjectId('69df560eb3ce5a690a189995'), ObjectId('69df560eb3ce5a690a189996'), ObjectId('69df560eb3ce5a690a189997'), ObjectId('69df560eb3ce5a690a189998'), ObjectId('69df560eb3ce5a690a189999'), ObjectId('69df560eb3ce5a690a18999a'), ObjectId('69df560eb3ce5a690a18999b'), ObjectId('69df560eb3ce5a690a18999c'), ObjectId('69df560eb3ce5a690a18999d'), ObjectId('69df560eb3ce5a690a18999e'), ObjectId('69df560eb3ce5a690a18999f'), ObjectId('69df560eb3ce5a690a1899a0'), ObjectId('69df560eb3ce5a690a1899a1'), ObjectId('69df560eb3ce5a690a1899a2'), ObjectId('69df560eb3ce5a690a1899a3'), ObjectId('69df560eb3ce5a690a1899a4'), ObjectId('69df560eb3ce5a690a1899a5'), ObjectId('69df560eb3ce5a690a1899a6'), ObjectId('69df560eb3ce5a690a1899a7'), ObjectId('69df560eb3ce5a690a1899a8'), ObjectId('69df560eb3ce5a690a1899a9'), ObjectId('69df560eb3ce5a690a1899aa'), ObjectId('69df560eb3ce5a690a1899ab'), ObjectId('69df560eb3ce5a690a1899ac'), ObjectId('69df560eb3ce5a690a1899ad'), ObjectId('69df560eb3ce5a690a1899ae'), ObjectId('69df560eb3ce5a690a1899af'), ObjectId('69df560eb3ce5a690a1899b0'), ObjectId('69df560eb3ce5a690a1899b1'), ObjectId('69df560eb3ce5a690a1899b2'), ObjectId('69df560eb3ce5a690a1899b3'), ObjectId('69df560eb3ce5a690a1899b4'), ObjectId('69df560eb3ce5a690a1899b5'), ObjectId('69df560eb3ce5a690a1899b6'), ObjectId('69df560eb3ce5a690a1899b7'), ObjectId('69df560eb3ce5a690a1899b8'), ObjectId('69df560eb3ce5a690a1899b9'), ObjectId('69df560eb3ce5a690a1899ba'), ObjectId('69df560eb3ce5a690a1899bb'), ObjectId('69df560eb3ce5a690a1899bc'), ObjectId('69df560eb3ce5a690a1899bd'), ObjectId('69df560eb3ce5a690a1899be'), ObjectId('69df560eb3ce5a690a1899bf'), ObjectId('69df560eb3ce5a690a1899c0'), ObjectId('69df560eb3ce5a690a1899c1'), ObjectId('69df560eb3ce5a690a1899c2'), ObjectId('69df560eb3ce5a690a1899c3'), ObjectId('69df560eb3ce5a690a1899c4'), ObjectId('69df560eb3ce5a690a1899c5'), ObjectId('69df560eb3ce5a690a1899c6'), ObjectId('69df560eb3ce5a690a1899c7'), ObjectId('69df560eb3ce5a690a1899c8'), ObjectId('69df560eb3ce5a690a1899c9'), ObjectId('69df560eb3ce5a690a1899ca'), ObjectId('69df560eb3ce5a690a1899cb'), ObjectId('69df560eb3ce5a690a1899cc'), ObjectId('69df560eb3ce5a690a1899cd'), ObjectId('69df560eb3ce5a690a1899ce'), ObjectId('69df560eb3ce5a690a1899cf'), ObjectId('69df560eb3ce5a690a1899d0'), ObjectId('69df560eb3ce5a690a1899d1'), ObjectId('69df560eb3ce5a690a1899d2'), ObjectId('69df560eb3ce5a690a1899d3'), ObjectId('69df560eb3ce5a690a1899d4'), ObjectId('69df560eb3ce5a690a1899d5'), ObjectId('69df560eb3ce5a690a1899d6'), ObjectId('69df560eb3ce5a690a1899d7'), ObjectId('69df560eb3ce5a690a1899d8'), ObjectId('69df560eb3ce5a690a1899d9'), ObjectId('69df560eb3ce5a690a1899da'), ObjectId('69df560eb3ce5a690a1899db'), ObjectId('69df560eb3ce5a690a1899dc'), ObjectId('69df560eb3ce5a690a1899dd'), ObjectId('69df560eb3ce5a690a1899de'), ObjectId('69df560eb3ce5a690a1899df'), ObjectId('69df560eb3ce5a690a1899e0'), ObjectId('69df560eb3ce5a690a1899e1'), ObjectId('69df560eb3ce5a690a1899e2'), ObjectId('69df560eb3ce5a690a1899e3'), ObjectId('69df560eb3ce5a690a1899e4'), ObjectId('69df560eb3ce5a690a1899e5'), ObjectId('69df560eb3ce5a690a1899e6'), ObjectId('69df560eb3ce5a690a1899e7'), ObjectId('69df560eb3ce5a690a1899e8'), ObjectId('69df560eb3ce5a690a1899e9'), ObjectId('69df560eb3ce5a690a1899ea'), ObjectId('69df560eb3ce5a690a1899eb'), ObjectId('69df560eb3ce5a690a1899ec'), ObjectId('69df560eb3ce5a690a1899ed'), ObjectId('69df560eb3ce5a690a1899ee'), ObjectId('69df560eb3ce5a690a1899ef'), ObjectId('69df560eb3ce5a690a1899f0'), ObjectId('69df560eb3ce5a690a1899f1'), ObjectId('69df560eb3ce5a690a1899f2'), ObjectId('69df560eb3ce5a690a1899f3'), ObjectId('69df560eb3ce5a690a1899f4'), ObjectId('69df560eb3ce5a690a1899f5'), ObjectId('69df560eb3ce5a690a1899f6'), ObjectId('69df560eb3ce5a690a1899f7'), ObjectId('69df560eb3ce5a690a1899f8'), ObjectId('69df560eb3ce5a690a1899f9'), ObjectId('69df560eb3ce5a690a1899fa'), ObjectId('69df560eb3ce5a690a1899fb'), ObjectId('69df560eb3ce5a690a1899fc'), ObjectId('69df560eb3ce5a690a1899fd'), ObjectId('69df560eb3ce5a690a1899fe'), ObjectId('69df560eb3ce5a690a1899ff'), ObjectId('69df560eb3ce5a690a189a00'), ObjectId('69df560eb3ce5a690a189a01'), ObjectId('69df560eb3ce5a690a189a02'), ObjectId('69df560eb3ce5a690a189a03'), ObjectId('69df560eb3ce5a690a189a04'), ObjectId('69df560eb3ce5a690a189a05'), ObjectId('69df560eb3ce5a690a189a06'), ObjectId('69df560eb3ce5a690a189a07'), ObjectId('69df560eb3ce5a690a189a08'), ObjectId('69df560eb3ce5a690a189a09'), ObjectId('69df560eb3ce5a690a189a0a'), ObjectId('69df560eb3ce5a690a189a0b'), ObjectId('69df560eb3ce5a690a189a0c'), ObjectId('69df560eb3ce5a690a189a0d'), ObjectId('69df560eb3ce5a690a189a0e'), ObjectId('69df560eb3ce5a690a189a0f'), ObjectId('69df560eb3ce5a690a189a10'), ObjectId('69df560eb3ce5a690a189a11'), ObjectId('69df560eb3ce5a690a189a12'), ObjectId('69df560eb3ce5a690a189a13'), ObjectId('69df560eb3ce5a690a189a14'), ObjectId('69df560eb3ce5a690a189a15'), ObjectId('69df560eb3ce5a690a189a16'), ObjectId('69df560eb3ce5a690a189a17'), ObjectId('69df560eb3ce5a690a189a18'), ObjectId('69df560eb3ce5a690a189a19'), ObjectId('69df560eb3ce5a690a189a1a'), ObjectId('69df560eb3ce5a690a189a1b'), ObjectId('69df560eb3ce5a690a189a1c'), ObjectId('69df560eb3ce5a690a189a1d'), ObjectId('69df560eb3ce5a690a189a1e'), ObjectId('69df560eb3ce5a690a189a1f'), ObjectId('69df560eb3ce5a690a189a20'), ObjectId('69df560eb3ce5a690a189a21'), ObjectId('69df560eb3ce5a690a189a22'), ObjectId('69df560eb3ce5a690a189a23'), ObjectId('69df560eb3ce5a690a189a24'), ObjectId('69df560eb3ce5a690a189a25'), ObjectId('69df560eb3ce5a690a189a26'), ObjectId('69df560eb3ce5a690a189a27'), ObjectId('69df560eb3ce5a690a189a28'), ObjectId('69df560eb3ce5a690a189a29'), ObjectId('69df560eb3ce5a690a189a2a'), ObjectId('69df560eb3ce5a690a189a2b'), ObjectId('69df560eb3ce5a690a189a2c'), ObjectId('69df560eb3ce5a690a189a2d'), ObjectId('69df560eb3ce5a690a189a2e'), ObjectId('69df560eb3ce5a690a189a2f'), ObjectId('69df560eb3ce5a690a189a30'), ObjectId('69df560eb3ce5a690a189a31'), ObjectId('69df560eb3ce5a690a189a32'), ObjectId('69df560eb3ce5a690a189a33'), ObjectId('69df560eb3ce5a690a189a34'), ObjectId('69df560eb3ce5a690a189a35'), ObjectId('69df560eb3ce5a690a189a36'), ObjectId('69df560eb3ce5a690a189a37'), ObjectId('69df560eb3ce5a690a189a38'), ObjectId('69df560eb3ce5a690a189a39'), ObjectId('69df560eb3ce5a690a189a3a'), ObjectId('69df560eb3ce5a690a189a3b'), ObjectId('69df560eb3ce5a690a189a3c'), ObjectId('69df560eb3ce5a690a189a3d'), ObjectId('69df560eb3ce5a690a189a3e'), ObjectId('69df560eb3ce5a690a189a3f'), ObjectId('69df560eb3ce5a690a189a40'), ObjectId('69df560eb3ce5a690a189a41'), ObjectId('69df560eb3ce5a690a189a42'), ObjectId('69df560eb3ce5a690a189a43'), ObjectId('69df560eb3ce5a690a189a44'), ObjectId('69df560eb3ce5a690a189a45'), ObjectId('69df560eb3ce5a690a189a46'), ObjectId('69df560eb3ce5a690a189a47'), ObjectId('69df560eb3ce5a690a189a48'), ObjectId('69df560eb3ce5a690a189a49'), ObjectId('69df560eb3ce5a690a189a4a'), ObjectId('69df560eb3ce5a690a189a4b'), ObjectId('69df560eb3ce5a690a189a4c'), ObjectId('69df560eb3ce5a690a189a4d'), ObjectId('69df560eb3ce5a690a189a4e'), ObjectId('69df560eb3ce5a690a189a4f'), ObjectId('69df560eb3ce5a690a189a50'), ObjectId('69df560eb3ce5a690a189a51'), ObjectId('69df560eb3ce5a690a189a52'), ObjectId('69df560eb3ce5a690a189a53'), ObjectId('69df560eb3ce5a690a189a54'), ObjectId('69df560eb3ce5a690a189a55'), ObjectId('69df560eb3ce5a690a189a56'), ObjectId('69df560eb3ce5a690a189a57'), ObjectId('69df560eb3ce5a690a189a58'), ObjectId('69df560eb3ce5a690a189a59'), ObjectId('69df560eb3ce5a690a189a5a'), ObjectId('69df560eb3ce5a690a189a5b'), ObjectId('69df560eb3ce5a690a189a5c'), ObjectId('69df560eb3ce5a690a189a5d'), ObjectId('69df560eb3ce5a690a189a5e'), ObjectId('69df560eb3ce5a690a189a5f'), ObjectId('69df560eb3ce5a690a189a60'), ObjectId('69df560eb3ce5a690a189a61'), ObjectId('69df560eb3ce5a690a189a62'), ObjectId('69df560eb3ce5a690a189a63'), ObjectId('69df560eb3ce5a690a189a64'), ObjectId('69df560eb3ce5a690a189a65'), ObjectId('69df560eb3ce5a690a189a66'), ObjectId('69df560eb3ce5a690a189a67'), ObjectId('69df560eb3ce5a690a189a68'), ObjectId('69df560eb3ce5a690a189a69'), ObjectId('69df560eb3ce5a690a189a6a'), ObjectId('69df560eb3ce5a690a189a6b'), ObjectId('69df560eb3ce5a690a189a6c'), ObjectId('69df560eb3ce5a690a189a6d'), ObjectId('69df560eb3ce5a690a189a6e'), ObjectId('69df560eb3ce5a690a189a6f'), ObjectId('69df560eb3ce5a690a189a70'), ObjectId('69df560eb3ce5a690a189a71'), ObjectId('69df560eb3ce5a690a189a72'), ObjectId('69df560eb3ce5a690a189a73'), ObjectId('69df560eb3ce5a690a189a74'), ObjectId('69df560eb3ce5a690a189a75'), ObjectId('69df560eb3ce5a690a189a76'), ObjectId('69df560eb3ce5a690a189a77'), ObjectId('69df560eb3ce5a690a189a78'), ObjectId('69df560eb3ce5a690a189a79'), ObjectId('69df560eb3ce5a690a189a7a'), ObjectId('69df560eb3ce5a690a189a7b'), ObjectId('69df560eb3ce5a690a189a7c'), ObjectId('69df560eb3ce5a690a189a7d'), ObjectId('69df560eb3ce5a690a189a7e'), ObjectId('69df560eb3ce5a690a189a7f'), ObjectId('69df560eb3ce5a690a189a80'), ObjectId('69df560eb3ce5a690a189a81'), ObjectId('69df560eb3ce5a690a189a82'), ObjectId('69df560eb3ce5a690a189a83'), ObjectId('69df560eb3ce5a690a189a84'), ObjectId('69df560eb3ce5a690a189a85'), ObjectId('69df560eb3ce5a690a189a86'), ObjectId('69df560eb3ce5a690a189a87'), ObjectId('69df560eb3ce5a690a189a88'), ObjectId('69df560eb3ce5a690a189a89'), ObjectId('69df560eb3ce5a690a189a8a'), ObjectId('69df560eb3ce5a690a189a8b'), ObjectId('69df560eb3ce5a690a189a8c'), ObjectId('69df560eb3ce5a690a189a8d'), ObjectId('69df560eb3ce5a690a189a8e'), ObjectId('69df560eb3ce5a690a189a8f'), ObjectId('69df560eb3ce5a690a189a90'), ObjectId('69df560eb3ce5a690a189a91'), ObjectId('69df560eb3ce5a690a189a92'), ObjectId('69df560eb3ce5a690a189a93'), ObjectId('69df560eb3ce5a690a189a94'), ObjectId('69df560eb3ce5a690a189a95'), ObjectId('69df560eb3ce5a690a189a96'), ObjectId('69df560eb3ce5a690a189a97'), ObjectId('69df560eb3ce5a690a189a98'), ObjectId('69df560eb3ce5a690a189a99'), ObjectId('69df560eb3ce5a690a189a9a'), ObjectId('69df560eb3ce5a690a189a9b'), ObjectId('69df560eb3ce5a690a189a9c'), ObjectId('69df560eb3ce5a690a189a9d'), ObjectId('69df560eb3ce5a690a189a9e'), ObjectId('69df560eb3ce5a690a189a9f'), ObjectId('69df560eb3ce5a690a189aa0'), ObjectId('69df560eb3ce5a690a189aa1'), ObjectId('69df560eb3ce5a690a189aa2'), ObjectId('69df560eb3ce5a690a189aa3'), ObjectId('69df560eb3ce5a690a189aa4'), ObjectId('69df560eb3ce5a690a189aa5'), ObjectId('69df560eb3ce5a690a189aa6'), ObjectId('69df560eb3ce5a690a189aa7'), ObjectId('69df560eb3ce5a690a189aa8'), ObjectId('69df560eb3ce5a690a189aa9'), ObjectId('69df560eb3ce5a690a189aaa'), ObjectId('69df560eb3ce5a690a189aab'), ObjectId('69df560eb3ce5a690a189aac'), ObjectId('69df560eb3ce5a690a189aad'), ObjectId('69df560eb3ce5a690a189aae'), ObjectId('69df560eb3ce5a690a189aaf'), ObjectId('69df560eb3ce5a690a189ab0'), ObjectId('69df560eb3ce5a690a189ab1'), ObjectId('69df560eb3ce5a690a189ab2'), ObjectId('69df560eb3ce5a690a189ab3'), ObjectId('69df560eb3ce5a690a189ab4'), ObjectId('69df560eb3ce5a690a189ab5'), ObjectId('69df560eb3ce5a690a189ab6'), ObjectId('69df560eb3ce5a690a189ab7'), ObjectId('69df560eb3ce5a690a189ab8'), ObjectId('69df560eb3ce5a690a189ab9'), ObjectId('69df560eb3ce5a690a189aba'), ObjectId('69df560eb3ce5a690a189abb'), ObjectId('69df560eb3ce5a690a189abc'), ObjectId('69df560eb3ce5a690a189abd'), ObjectId('69df560eb3ce5a690a189abe'), ObjectId('69df560eb3ce5a690a189abf'), ObjectId('69df560eb3ce5a690a189ac0'), ObjectId('69df560eb3ce5a690a189ac1'), ObjectId('69df560eb3ce5a690a189ac2'), ObjectId('69df560eb3ce5a690a189ac3'), ObjectId('69df560eb3ce5a690a189ac4'), ObjectId('69df560eb3ce5a690a189ac5'), ObjectId('69df560eb3ce5a690a189ac6'), ObjectId('69df560eb3ce5a690a189ac7'), ObjectId('69df560eb3ce5a690a189ac8'), ObjectId('69df560eb3ce5a690a189ac9'), ObjectId('69df560eb3ce5a690a189aca'), ObjectId('69df560eb3ce5a690a189acb'), ObjectId('69df560eb3ce5a690a189acc'), ObjectId('69df560eb3ce5a690a189acd'), ObjectId('69df560eb3ce5a690a189ace'), ObjectId('69df560eb3ce5a690a189acf'), ObjectId('69df560eb3ce5a690a189ad0'), ObjectId('69df560eb3ce5a690a189ad1'), ObjectId('69df560eb3ce5a690a189ad2'), ObjectId('69df560eb3ce5a690a189ad3'), ObjectId('69df560eb3ce5a690a189ad4'), ObjectId('69df560eb3ce5a690a189ad5'), ObjectId('69df560eb3ce5a690a189ad6'), ObjectId('69df560eb3ce5a690a189ad7'), ObjectId('69df560eb3ce5a690a189ad8'), ObjectId('69df560eb3ce5a690a189ad9'), ObjectId('69df560eb3ce5a690a189ada'), ObjectId('69df560eb3ce5a690a189adb'), ObjectId('69df560eb3ce5a690a189adc'), ObjectId('69df560eb3ce5a690a189add'), ObjectId('69df560eb3ce5a690a189ade'), ObjectId('69df560eb3ce5a690a189adf'), ObjectId('69df560eb3ce5a690a189ae0'), ObjectId('69df560eb3ce5a690a189ae1'), ObjectId('69df560eb3ce5a690a189ae2'), ObjectId('69df560eb3ce5a690a189ae3'), ObjectId('69df560eb3ce5a690a189ae4'), ObjectId('69df560eb3ce5a690a189ae5'), ObjectId('69df560eb3ce5a690a189ae6'), ObjectId('69df560eb3ce5a690a189ae7'), ObjectId('69df560eb3ce5a690a189ae8'), ObjectId('69df560eb3ce5a690a189ae9'), ObjectId('69df560eb3ce5a690a189aea'), ObjectId('69df560eb3ce5a690a189aeb'), ObjectId('69df560eb3ce5a690a189aec'), ObjectId('69df560eb3ce5a690a189aed'), ObjectId('69df560eb3ce5a690a189aee'), ObjectId('69df560eb3ce5a690a189aef'), ObjectId('69df560eb3ce5a690a189af0'), ObjectId('69df560eb3ce5a690a189af1'), ObjectId('69df560eb3ce5a690a189af2'), ObjectId('69df560eb3ce5a690a189af3'), ObjectId('69df560eb3ce5a690a189af4'), ObjectId('69df560eb3ce5a690a189af5'), ObjectId('69df560eb3ce5a690a189af6'), ObjectId('69df560eb3ce5a690a189af7'), ObjectId('69df560eb3ce5a690a189af8'), ObjectId('69df560eb3ce5a690a189af9'), ObjectId('69df560eb3ce5a690a189afa'), ObjectId('69df560eb3ce5a690a189afb'), ObjectId('69df560eb3ce5a690a189afc'), ObjectId('69df560eb3ce5a690a189afd'), ObjectId('69df560eb3ce5a690a189afe'), ObjectId('69df560eb3ce5a690a189aff'), ObjectId('69df560eb3ce5a690a189b00'), ObjectId('69df560eb3ce5a690a189b01'), ObjectId('69df560eb3ce5a690a189b02'), ObjectId('69df560eb3ce5a690a189b03'), ObjectId('69df560eb3ce5a690a189b04'), ObjectId('69df560eb3ce5a690a189b05'), ObjectId('69df560eb3ce5a690a189b06'), ObjectId('69df560eb3ce5a690a189b07'), ObjectId('69df560eb3ce5a690a189b08'), ObjectId('69df560eb3ce5a690a189b09'), ObjectId('69df560eb3ce5a690a189b0a'), ObjectId('69df560eb3ce5a690a189b0b'), ObjectId('69df560eb3ce5a690a189b0c'), ObjectId('69df560eb3ce5a690a189b0d'), ObjectId('69df560eb3ce5a690a189b0e'), ObjectId('69df560eb3ce5a690a189b0f'), ObjectId('69df560eb3ce5a690a189b10'), ObjectId('69df560eb3ce5a690a189b11'), ObjectId('69df560eb3ce5a690a189b12'), ObjectId('69df560eb3ce5a690a189b13'), ObjectId('69df560eb3ce5a690a189b14'), ObjectId('69df560eb3ce5a690a189b15'), ObjectId('69df560eb3ce5a690a189b16'), ObjectId('69df560eb3ce5a690a189b17'), ObjectId('69df560eb3ce5a690a189b18'), ObjectId('69df560eb3ce5a690a189b19'), ObjectId('69df560eb3ce5a690a189b1a'), ObjectId('69df560eb3ce5a690a189b1b'), ObjectId('69df560eb3ce5a690a189b1c'), ObjectId('69df560eb3ce5a690a189b1d'), ObjectId('69df560eb3ce5a690a189b1e'), ObjectId('69df560eb3ce5a690a189b1f'), ObjectId('69df560eb3ce5a690a189b20'), ObjectId('69df560eb3ce5a690a189b21'), ObjectId('69df560eb3ce5a690a189b22'), ObjectId('69df560eb3ce5a690a189b23'), ObjectId('69df560eb3ce5a690a189b24'), ObjectId('69df560eb3ce5a690a189b25'), ObjectId('69df560eb3ce5a690a189b26'), ObjectId('69df560eb3ce5a690a189b27'), ObjectId('69df560eb3ce5a690a189b28'), ObjectId('69df560eb3ce5a690a189b29'), ObjectId('69df560eb3ce5a690a189b2a'), ObjectId('69df560eb3ce5a690a189b2b'), ObjectId('69df560eb3ce5a690a189b2c'), ObjectId('69df560eb3ce5a690a189b2d'), ObjectId('69df560eb3ce5a690a189b2e'), ObjectId('69df560eb3ce5a690a189b2f'), ObjectId('69df560eb3ce5a690a189b30'), ObjectId('69df560eb3ce5a690a189b31'), ObjectId('69df560eb3ce5a690a189b32'), ObjectId('69df560eb3ce5a690a189b33'), ObjectId('69df560eb3ce5a690a189b34'), ObjectId('69df560eb3ce5a690a189b35'), ObjectId('69df560eb3ce5a690a189b36'), ObjectId('69df560eb3ce5a690a189b37'), ObjectId('69df560eb3ce5a690a189b38'), ObjectId('69df560eb3ce5a690a189b39'), ObjectId('69df560eb3ce5a690a189b3a'), ObjectId('69df560eb3ce5a690a189b3b'), ObjectId('69df560eb3ce5a690a189b3c'), ObjectId('69df560eb3ce5a690a189b3d'), ObjectId('69df560eb3ce5a690a189b3e'), ObjectId('69df560eb3ce5a690a189b3f'), ObjectId('69df560eb3ce5a690a189b40'), ObjectId('69df560eb3ce5a690a189b41'), ObjectId('69df560eb3ce5a690a189b42'), ObjectId('69df560eb3ce5a690a189b43'), ObjectId('69df560eb3ce5a690a189b44'), ObjectId('69df560eb3ce5a690a189b45'), ObjectId('69df560eb3ce5a690a189b46'), ObjectId('69df560eb3ce5a690a189b47'), ObjectId('69df560eb3ce5a690a189b48'), ObjectId('69df560eb3ce5a690a189b49'), ObjectId('69df560eb3ce5a690a189b4a'), ObjectId('69df560eb3ce5a690a189b4b'), ObjectId('69df560eb3ce5a690a189b4c'), ObjectId('69df560eb3ce5a690a189b4d'), ObjectId('69df560eb3ce5a690a189b4e'), ObjectId('69df560eb3ce5a690a189b4f'), ObjectId('69df560eb3ce5a690a189b50'), ObjectId('69df560eb3ce5a690a189b51'), ObjectId('69df560eb3ce5a690a189b52'), ObjectId('69df560eb3ce5a690a189b53'), ObjectId('69df560eb3ce5a690a189b54'), ObjectId('69df560eb3ce5a690a189b55'), ObjectId('69df560eb3ce5a690a189b56'), ObjectId('69df560eb3ce5a690a189b57'), ObjectId('69df560eb3ce5a690a189b58'), ObjectId('69df560eb3ce5a690a189b59'), ObjectId('69df560eb3ce5a690a189b5a'), ObjectId('69df560eb3ce5a690a189b5b'), ObjectId('69df560eb3ce5a690a189b5c'), ObjectId('69df560eb3ce5a690a189b5d'), ObjectId('69df560eb3ce5a690a189b5e'), ObjectId('69df560eb3ce5a690a189b5f'), ObjectId('69df560eb3ce5a690a189b60'), ObjectId('69df560eb3ce5a690a189b61'), ObjectId('69df560eb3ce5a690a189b62'), ObjectId('69df560eb3ce5a690a189b63'), ObjectId('69df560eb3ce5a690a189b64'), ObjectId('69df560eb3ce5a690a189b65'), ObjectId('69df560eb3ce5a690a189b66'), ObjectId('69df560eb3ce5a690a189b67'), ObjectId('69df560eb3ce5a690a189b68'), ObjectId('69df560eb3ce5a690a189b

In [23]:
recs = collection.find()
type(recs)

pymongo.synchronous.cursor.Cursor

In [24]:
# collection.find_one()

for i, j in enumerate(recs):
    print(i, j)
    break

0 {'_id': ObjectId('69df560eb3ce5a690a18995c'), 'case_id': 'EZYV01', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 14513, 'yr_of_estab': 2007, 'region_of_employment': 'West', 'prevailing_wage': 592.2029, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}

In [25]:
df = pd.DataFrame(list(recs))
df.head()

,_id,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,69df560eb3ce5a690a18995d,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.65,Year,Y,Certified
1,69df560eb3ce5a690a18995e,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.86,Year,Y,Denied
2,69df560eb3ce5a690a18995f,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.03,Year,Y,Denied
3,69df560eb3ce5a690a189960,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.39,Year,Y,Certified
4,69df560eb3ce5a690a189961,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.14,Year,Y,Certified

In [27]:
if "_id" in df.columns:
    df = df.drop(columns=["_id"])

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.65,Year,Y,Certified
1,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.86,Year,Y,Denied
2,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.03,Year,Y,Denied
3,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.39,Year,Y,Certified
4,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.14,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25474,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25475,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25476,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25477,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25478,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [32]:
from from_root import from_root

print(from_root())

C:\Users\hp

In [ ]:
import os
from pathlib import Path

Path(__file__).resolve().parent

NameError: name '__file__' is not defined

In [15]:
import sys

try:
    2+4
    3+4
    1 / 0
except:
    _, _, exc_tb = sys.exc_info()
    print(exc_tb)

<traceback object at 0x0000025A457E28C0>

In [9]:
error[2]

In [16]:
import sys

def test():
    a = 10
    b = a / 0

try:
    test()
except:
    _, _, tb = sys.exc_info()
    print(tb.tb_frame)

<frame at 0x0000025A4346DE10, file 'C:\\Users\\hp\\AppData\\Local\\Temp\\ipykernel_19596\\3596583320.py', line 11, code <module>>

In [19]:
tb.tb_frame[0]

TypeError: 'frame' object is not subscriptable